# Generated by Django 2.1 on 2018-08-26 14:08

from django.db import migrations, models
import mainsite.custom_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id', mainsite.custom_fields.PositiveBigIntegerField(verbose_name='ツイッターID')),
                ('pref', models.CharField(max_length=255, verbose_name='都道府県')),
                ('evaluation', mainsite.custom_fields.PositiveBigIntegerField(default=0, verbose_name='評価数')),
            ],
        ),
    ]
