# Generated by Django 2.1 on 2018-08-26 15:35

from django.db import migrations
import mainsite.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='held_count',
            field=mainsite.custom_fields.PositiveBigIntegerField(default=0, verbose_name='開催数'),
        ),
    ]
