# Generated by Django 2.1 on 2018-08-27 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_account_held_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('at_time', models.DateTimeField(null=True, verbose_name='開催日時')),
                ('capacity', models.IntegerField(verbose_name='募集人数')),
                ('location_lat', models.FloatField(null=True, verbose_name='緯度')),
                ('location_lng', models.FloatField(null=True, verbose_name='経度')),
                ('recruitment_start', models.DateField(verbose_name='募集開始')),
                ('recruitment_end', models.DateField(verbose_name='募集終了')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Account')),
            ],
        ),
    ]
