# Generated by Django 2.1 on 2018-08-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_offlineparty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlineparty',
            name='at_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='開催日時'),
        ),
        migrations.AlterField(
            model_name='offlineparty',
            name='location_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='offlineparty',
            name='location_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='経度'),
        ),
    ]
