# Generated by Django 2.1 on 2018-08-27 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20180827_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='カテゴリ')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Account')),
            ],
        ),
    ]
