# Generated by Django 2.1 on 2018-08-28 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20180827_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoiningOfflineParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Account')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.OfflineParty')),
            ],
        ),
    ]
