# Generated by Django 2.1 on 2018-08-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_offlineparty_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountcategory',
            name='account',
        ),
        migrations.RemoveField(
            model_name='accountcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='account',
            name='category',
            field=models.ManyToManyField(to='mainsite.Category'),
        ),
        migrations.DeleteModel(
            name='AccountCategory',
        ),
    ]
