# Generated by Django 2.1 on 2018-08-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_auto_20180828_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlineparty',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='offlineparty',
            name='access_token_secret',
        ),
    ]
