# Generated by Django 2.1 on 2018-08-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_auto_20180830_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineparty',
            name='access_token',
            field=models.TextField(default='', verbose_name='アクセストークン'),
        ),
        migrations.AddField(
            model_name='offlineparty',
            name='access_token_secret',
            field=models.TextField(default='', verbose_name='アクセストークンシークレット'),
        ),
    ]
